route:
  group_by: ['alertname']
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'https://webhook.site/b509d203-d35b-4ed1-a856-901d09ea6117' # can get the url from webhook.site

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']